CREATE INDEX ReportFormConfig$COMPOSITE20 ON ReportFormConfig(creator)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX ReportFormConfig$COMPOSITE21 ON ReportFormConfig(modifier)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
